ShowcaseScreen:
    name: 'Instructions'

    BoxLayout:
        orientation: "vertical"

        FloatLayout:
            canvas:
                Color:
                    rgb: 1, 1, 1
                Rectangle:
                    source: 'data/images/background.jpg'
                    size: self.size

        Button:
            size_hint_y: None
            text: 'Button normal'
            height: '48dp'
            on_release: app.go_next_screen()