ShowcaseScreen:
    name: 'Instructions'

    Widget:

        Scatter:
            id: scatter
            size_hint: None, None
            size: image.size
            do_rotation: False
            do_scale: False
            do_translation: False
            pos: 300,200

            Image:
                id: image
                source: 'data/faust_github.jpg'
                size: 300,200
    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Next'