ShowcaseScreen:
    name: 'Scatter'

    Widget:

        # Scatter:
        #     id: scatter
        size_hint: None, None
        size: image.size

   AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        
        Image:
            id: image
            source: 'data/icons/bug.png'
            size: self.texture_size
            pos: 10, 10   

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button normal'
        on_release: image.reload()
