ShowcaseScreen:
    name: 'Scatter'

    Widget:

        # Scatter:
        #     id: scatter
        size_hint: None, None
        size: image.size

        Image:
            id: image
            source: 'data/faust_github.jpg'
            size: 300, 400
            pos_hint: {"x":0.35, "y":0.3} 

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button normal'
        on_release: image.reload()
