ShowcaseScreen:
    name: 'Scatter'

    Widget:

        # Scatter:
        #     id: scatter
        size_hint: None, None
        size: image.size


        Image:
            id: image
            source: 'data/icons/bug.png'
            size: self.texture_size
            size_hint: 0.3, 0.4
            pos_hint: {'center_x': 0.5, 'center_y': 0.75}

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button normal'
        on_release: image.reload()
